import { api } from "./client";

export const usersApi = { me: () => api.get<{ user: Record<string, unknown> }>("/api/users/me"), all: () => api.get<{ users: Record<string, unknown>[] }>("/api/users") };
export const businessApi = { get: () => api.get<{ business: Business }>("/api/business"), create: (body: unknown) => api.post<{ business: Business }>("/api/business", body), patch: (body: unknown) => api.patch<{ business: Business }>("/api/business", body), slug: (slug: string) => api.get<{ available: boolean }>(`/api/business/slug-available?slug=${encodeURIComponent(slug)}`) };
export const menuApi = { items: () => api.get<{ items: Item[] }>("/api/menu/items"), categories: () => api.get<{ categories: Category[] }>("/api/menu/categories"), createItem: (body: unknown) => api.post<{ item: Item }>("/api/menu/items", body), patchItem: (id: number, body: unknown) => api.patch<{ item: Item }>(`/api/menu/items/${id}`, body), unlist: (id: number) => api.patch<{ item: Item }>(`/api/menu/items/${id}/unlist`, {}), createCategory: (name: string) => api.post<{ category: Category }>("/api/menu/categories", { name }), renameCategory: (id: number, name: string) => api.patch<{ category: Category }>(`/api/menu/categories/${id}`, { name }), deleteCategory: (id: number) => api.delete<{ category: Category; itemsUncategorized: number }>(`/api/menu/categories/${id}`) };
export const ordersApi = { list: (query = "") => api.get<{ orders: Order[] }>(`/api/orders${query ? `?${query}` : ""}`), get: (id: number) => api.get<{ order: Order }>(`/api/orders/${id}`), patch: (id: number, body: unknown) => api.patch<{ order: Order }>(`/api/orders/${id}`, body), tracking: (id: number) => api.post<{ trackingUrl: string }>(`/api/orders/${id}/tracking-link`) };
export const publicApi = { business: (slug: string) => api.get<{ business: PublicBusiness }>(`/api/public/businesses/${slug}`), menu: (slug: string) => api.get<{ menu: { categories: Array<Category & { items: Item[] }> } }>(`/api/public/businesses/${slug}/menu`), placeOrder: (slug: string, body: unknown) => api.post<{ order: unknown; trackingToken: string; trackingUrl: string }>(`/api/public/businesses/${slug}/orders`, body), track: (token: string) => api.get<{ order: TrackingOrder }>(`/api/public/track/${token}`) };
export const uploadsApi = { post: (path: string, file: File) => api.upload<{ image: string | null }>(`/api/uploads/${path}`, file), remove: (path: string) => api.delete<{ image: null }>(`/api/uploads/${path}`) };

export type Business = { id: number; name: string; description: string | null; businessLink: string; logo: string | null; banner: string | null; instagram: string | null; tiktok: string | null; facebook: string | null; ownerContact: string | null; contacts?: string[]; isAcceptingOrders: boolean };
export type PublicBusiness = Omit<Business, "id" | "businessLink" | "ownerContact">;
export type Category = { id: number; name: string; businessId: number };
export type Item = { id: number; name: string; description: string | null; price: number; categoryId: number | null; isListed: boolean; inStock: boolean; image: string | null; priority: number };
export type Order = { id: number; customerName: string; customerPhone: string; customerNote: string | null; address: string; status: string; paymentStatus: string; paymentMethod: string | null; price: number; expectedDeliveryTime: string | null; createdAt: string; trackingUrl: string | null; trackingLink?: string; items?: Array<{ name: string; quantity: number; unitPrice: number; totalPrice: number; extraNote: string | null }> };
export type TrackingOrder = Pick<Order, "id" | "status" | "paymentStatus" | "price" | "expectedDeliveryTime"> & { businessName: string; businessLogo: string | null; items: Array<{ name: string; quantity: number; totalPrice: number }> };
